# Form implementation generated from reading ui file 'patientAlert.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("#Form { background: rgb(200, 0, 0); }\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OBSpatient = QtWidgets.QLabel(parent=Form)
        self.OBSpatient.setStyleSheet("#OBSpatient { background: rgb(255, 172, 248) }")
        self.OBSpatient.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.OBSpatient.setObjectName("OBSpatient")
        self.verticalLayout_2.addWidget(self.OBSpatient)
        self.okButton = QtWidgets.QPushButton(parent=Form)
        self.okButton.setStyleSheet("QPushButton\n"
"{\n"
" background-color: rgb(255, 172, 248);\n"
"  border-width: 0px;\n"
"  border-radius: 3px;\n"
"}\n"
"QPushButton:hover { background-color: #66c011; }")
        self.okButton.setObjectName("okButton")
        self.verticalLayout_2.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.OBSpatient.setText(_translate("Form", "OBS: Patienten har en multiresistent bakterieinfektion"))
        self.okButton.setText(_translate("Form", "Forstået"))


#Her starter min kode
        # Connect søg patient knappen to function that opens patientsøgningen
        self.okButton.clicked.connect(self.patientsoegning)

    def patientsoegning(self):
        import subprocess
        subprocess.run(["python", "patientjournal.py"])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
