# Form implementation generated from reading ui file 'personoplysninger.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 634)
        Form.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_2.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_9.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_5.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_6.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_7.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_8.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_3.addWidget(self.lineEdit_8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_9.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_10.addWidget(self.lineEdit_9)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "Personoplysninger"))
        self.label_8.setText(_translate("Form", "Patient ID"))
        self.label_7.setText(_translate("Form", "Adresse"))
        self.label_6.setText(_translate("Form", "CPR"))
        self.label_5.setText(_translate("Form", "Efternavn"))
        self.label_4.setText(_translate("Form", "Fornavn"))
        self.label_3.setText(_translate("Form", "Køn"))
        self.label.setText(_translate("Form", "Alder"))
        self.label_2.setText(_translate("Form", "Telefon"))
        self.label_10.setText(_translate("Form", "Multiresistent(1)"))
        self.pushButton_3.setText(_translate("Form", "Save"))
        self.pushButton_2.setText(_translate("Form", "Update"))
        self.pushButton.setText(_translate("Form", "Delete"))

#her starter vores kode

        #SAVE PERSONDATA IN DATABASE
        self.pushButton_3.clicked.connect(self.new_patient)
        self.pushButton.clicked.connect(self.delete_patient)
        self.pushButton_2.clicked.connect(self.update_patient)

    def new_patient(self):
        import subprocess
        import mysql.connector
        from mysql.connector import errorcode
        db = mysql.connector.connect(user='root',
                                     password='lillemand123',
                                     host='127.0.0.1',
                                     database='mydb')

        #alle kolonner i Patient table i databasen
        Patient_ID = self.lineEdit_2.text()
        Adresse = self.lineEdit_3.text()
        CPR = self.lineEdit_4.text()
        Efternavn = self.lineEdit_5.text()
        Fornavn = self.lineEdit_6.text()
        Køn = self.lineEdit_7.text()
        Alder = self.lineEdit_8.text()
        Telefon = self.lineEdit.text()
        Multiresistent_status = self.lineEdit_9.text()

        try:
            conn = db
            cursor = conn.cursor()
            query = "INSERT INTO `mydb`.`Patient` (`Patient_ID`, `CPR`, `Fornavn`, `Efternavn`, `Adresse`, `Køn`, `Alder`, `Telefon`, `Multiresistent_status`)" \
                    f"VALUES ('{Patient_ID}', '{CPR}', '{Fornavn}', '{Efternavn}', '{Adresse}', '{Køn}', '{Alder}', '{Telefon}', '{Multiresistent_status}')"
            cursor.execute(query)
            conn.commit()
            print("Patient inserted successfully!")
        except Exception as e:
            print(e)

    def delete_patient(self):
        import mysql.connector
        from mysql.connector import errorcode

        # Establish the database connection
        db = mysql.connector.connect(user='root',
                                     password='lillemand123',
                                     host='127.0.0.1',
                                     database='mydb')

        # Retrieve the patient ID you want to remove
        CPR = self.lineEdit_4.text()

        try:
            conn = db
            cursor = conn.cursor()

            # Check if the patient exists
            select_query = f"SELECT * FROM `mydb`.`Patient` WHERE `CPR` = '{CPR}'"
            cursor.execute(select_query)
            result = cursor.fetchone()

            if result:
                # Delete the patient
                delete_query = f"DELETE FROM `mydb`.`Patient` WHERE `CPR` = '{CPR}'"
                cursor.execute(delete_query)
                conn.commit()
                print("Patient removed successfully!")
            else:
                print("Patient not found in the database.")
        except Exception as e:
            print(e)

        # Close the database connection
        db.close()

    def update_patient(self):
        import mysql.connector
        from mysql.connector import errorcode

        # Establish the database connection
        db = mysql.connector.connect(user='root',
                                     password='lillemand123',
                                     host='127.0.0.1',
                                     database='mydb')

        #alle kolonner i Patient table i databasen
        Patient_ID = self.lineEdit_2.text()
        Adresse = self.lineEdit_3.text()
        CPR = self.lineEdit_4.text()
        Efternavn = self.lineEdit_5.text()
        Fornavn = self.lineEdit_6.text()
        Køn = self.lineEdit_7.text()
        Alder = self.lineEdit_8.text()
        Telefon = self.lineEdit.text()
        Multiresistent_status = self.lineEdit_9.text()

        try:
            conn = db
            cursor = conn.cursor()
            query = "UPDATE mydb.Patient " \
                    f"SET Adresse = '{Adresse}', CPR = '{CPR}', Efternavn = '{Efternavn}', Fornavn = '{Fornavn}', Køn = '{Køn}', Alder = '{Alder}', Telefon = '{Telefon}', Multiresistent_status = '{Multiresistent_status}'"\
                    f"WHERE Patient_ID = '{Patient_ID}' "
            cursor.execute(query)
            conn.commit()
            print("Patient inserted successfully!")
        except Exception as e:
            print(e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
