@startuml
top to bottom direction

interface SP_system {
Medical_history: string
Medication_history: string
Treatment_plans: string
PDI: string
Lab_resultater: string
Diagnostiske_billeder: billeder
Registrering()
}

class Hospital {
Hospitalsnavn: string
Region: string
Kommune: string
Vejnavn: string
Vejnummer: int
}

class Relateret_person {
Fornavn: string
Efternavn: string
Alder: int
Køn: string
CPR: string
Adresse: string
Telefon: int
}

class Medarbejder {
medarbejderID: int
afdeling: string
job_type: string
}

class Patient {
Patient_ID: int
}

class Users {
sername: string
Password: string
}

class Læge {
Login_status: bool
Konsulterer()
Tager_prøve()
}

class Laboratorie {
prøve_resultater: string
Multi_resistent_sygdom: bool
analyserer_prøve()
}

class Multiresistent_register {
Patient_CPR: string
MRS_type: string
tilføj_positiv()
fjern_negativ()
}

class SP_interface {
Current_user_ID: int
verificer_login()
}

class Alert_system {
Varsels_tekst: sting
Alert_send()
Check_CPR()
}

class EPJ {
}

Hospital "1..*" --o SP_system
Relateret_person "1..*" --> Hospital: har noget at gøre med
Medarbejder --|> Relateret_person
Patient --|> Relateret_person
Users --|> Medarbejder
Læge --|> Users
Læge --> "1..*" Patient: consults
Læge "1..*" --> Laboratorie: sender prøve
Laboratorie "1..*" --> Multiresistent_register: with CPR
SP_interface --* SP_system: er en del af
Alert_system --> SP_interface: sends alert
Multiresistent_register <- Alert_system: Check CPR
Patient *-- EPJ
EPJ "1..*" --> SP_interface: visible on



@enduml
